# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('mood', models.CharField(max_length=10)),
            ],
        ),
    ]
